[book]
authors = ["Starknet community, with support from Starkware and Voyager"]
language = "en"
multilingual = false
src = "src"
title = "El Lenguaje de Programación Cairo"

[output.html.playground]
runnable = false